name: drupal9-view
recipe: drupal9
config:
  php: '7.4'
  composer_version: '1.10.1'
  webroot: .
  database: mariadb
  xdebug: true
services:
  appserver:
    build:
      - composer install
tooling:
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: "https://drupal9-view.lndo.site"
